"""updated invoices

Revision ID: f774db7bdaeb
Revises: e762f6d88627
Create Date: 2025-07-17 10:10:36.395695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f774db7bdaeb'
down_revision = 'e762f6d88627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('order_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('order_id'), ['order_id'], unique=True)

    # ### end Alembic commands ###
